#!/bin/bash

COUNTRY=${1:-DACH}
SPLITTER_MAXNODES=1400000
#SPLITTER_MAXNODES=700000
SPLITTER_OVERLAP=0
RETVAL=0

# Split country osm data into tiles
SplitIntoTiles()
{
    SRCDIR=$1
    OUTPUTDIR=build/"$COUNTRY"/$2

    rm -rf "$OUTPUTDIR"
    mkdir -p "$OUTPUTDIR"
    if [ -f tk-osm/basemap/areas."$COUNTRY".list -a "$OUTPUTDIR" == "tiles" ]; then
	AREALIST="--split-file=tk-osm/basemap/areas.$COUNTRY.list"
    fi

    PRECOMP_SEA=""
    if [ -e data/sea/current ]; then
	PRECOMP_SEA="--precomp-sea=data/sea/current"
    fi

    tilesplitter --mapid="$TILEID" --max-nodes=${SPLITTER_MAXNODES} --overlap=${SPLITTER_OVERLAP} --keep-complete=true --max-areas=1024 $PRECOMP_SEA --geonames-file=tk-osm/scripts/cities/${COUNTRY_ABBR}.txt  --description="$DESC" --output=pbf --output-dir="$OUTPUTDIR" "$SRCDIR/$COUNTRY.$SUFFIX" $AREALIST
    if [ $? -ne 0 -o ! -f "$OUTPUTDIR/${TILEID}.osm.pbf" ] ; then
	echo "tilesplitter failed!"
	exit 1
    fi
    test -f "$SRCDIR/timestamp.txt" && cp -v "$SRCDIR/timestamp.txt" "$OUTPUTDIR"
}

SUFFIX="osm.pbf"

case "$COUNTRY" in
SRTM-*)
  COUNTRY=${COUNTRY##SRTM-}
  MAPS="srtm"
  SPLITTER_MAXNODES=3000000
  case "$COUNTRY" in
  benelux)
    TILEID=71700501
    COUNTRY_ABBR="BNL"
    ;;
  channel_islands)
    TILEID=72200001
    COUNTRY_ABBR="GBR"
    ;;
  croatia)
    TILEID=72300001
    COUNTRY_ABBR="HRV"
    ;;
  czech_republic)
    TILEID=71300501
    COUNTRY_ABBR="CZE"
    ;;
  DACH)
    TILEID=71208001
    COUNTRY_ABBR="DACH"
    ;;
  europe)
    TILEID=71105001
    COUNTRY_ABBR="EU"
    ;;
  france)
    TILEID=71609001
    COUNTRY_ABBR="FRA"
    ;;
  iceland)
    TILEID=72550501
    COUNTRY_ABBR="ISL"
    ;;
  india)
    TILEID=72102001
    COUNTRY_ABBR="IND"
    ;;
  ireland)
    TILEID=71340501
    COUNTRY_ABBR="IRL"
    ;;
  italy)
    TILEID=71809001
    COUNTRY_ABBR="ITA"
    ;;
  canada)
    TILEID=71408001
    COUNTRY_ABBR="CAN"
    ;;
  portugal)
    TILEID=72502001
    COUNTRY_ABBR="PRT"
    ;;
  scandinavia)
    TILEID=71909001
    COUNTRY_ABBR="DNS"
    ;;
  spain)
    TILEID=72402001
    COUNTRY_ABBR="ESP"
    ;;
  canary_islands)
    TILEID=72402701
    COUNTRY_ABBR="ESP"
    ;;
  usa*)
    TILEID=71510001
    COUNTRY_ABBR="USA"
    ;;
  new_zealand)
    TILEID=72601001
    COUNTRY_ABBR="NZL"
    ;;
  monaco)
    TILEID=72681001
    COUNTRY_ABBR="MCO"
    ;;
  singapore)
    TILEID=72661001
    COUNTRY_ABBR="SGP"
    ;;
  great_britain)
    TILEID=72000001
    COUNTRY_ABBR="GBR"
    ;;
  germany)
    TILEID=7169X001
    COUNTRY_ABBR="DEU"
    ;;
  austria)
    TILEID=71642001
    COUNTRY_ABBR="AUT"
    ;;
  switzerland)
    TILEID=71652001
    COUNTRY_ABBR="CHE"
    ;;
  *)
    echo "SRTM-Country unknown!"
    exit 1
    ;;
  esac
  ;;
DACH)
    MAPS="basemap-noPOI bicycling oepnv wanderwege" # marine address fixme
    TILEID=71200001
    COUNTRY_ABBR="DACH"
    ;;
germany)
    MAPS="basemap" # mkgmap
    TILEID=71690001
    COUNTRY_ABBR="DEU"
    ;;
austria)
    MAPS="basemap"
    TILEID=71640001
    COUNTRY_ABBR="AUT"
    ;;
switzerland)
    MAPS="basemap"
    TILEID=71650001
    COUNTRY_ABBR="CHE"
    ;;
europe)
    MAPS="basemap bicycling oepnv wanderwege" # marine streets fixme
    TILEID=71100001
    COUNTRY_ABBR="EU"
    #SPLITTER_MAXNODES=1200000
    ;;
benelux)
    MAPS="basemap bicycling oepnv wanderwege" # marine fixme
    TILEID=71700001
    COUNTRY_ABBR="BNL"
    ;;
channel_islands)
    MAPS="basemap bicycling oepnv" # wanderwege marine fixme
    TILEID=72200001
    COUNTRY_ABBR="GBR"
    ;;
croatia)
    MAPS="basemap bicycling oepnv wanderwege" # marine marine fixme
    TILEID=72300001
    COUNTRY_ABBR="HRV"
    ;;
czech_republic)
    MAPS="basemap bicycling oepnv wanderwege" # marine fixme
    TILEID=71300001
    COUNTRY_ABBR="CZE"
    ;;
ireland)
    MAPS="basemap bicycling oepnv wanderwege" # marine fixme
    TILEID=71340001
    COUNTRY_ABBR="IRL"
    ;;
france)
    MAPS="basemap bicycling oepnv wanderwege" # marine fixme
    TILEID=71600001
    COUNTRY_ABBR="FRA"
    ;;
great_britain)
    MAPS="basemap bicycling oepnv wanderwege" # marine fixme
    TILEID=72000001
    COUNTRY_ABBR="GBR"
    ;;
iceland)
    MAPS="basemap wanderwege oepnv bicycling" # marine fixme
    TILEID=72550001
    COUNTRY_ABBR="ISL"
    ;;
india)
    MAPS="basemap" # bicycling oepnv marine wanderwege fixme
    TILEID=72100001
    COUNTRY_ABBR="IND"
    ;;
italy)
    MAPS="basemap bicycling oepnv wanderwege" # marine fixme
    TILEID=71800001
    COUNTRY_ABBR="ITA"
    ;;
canada)
    MAPS="basemap wanderwege" # bicycling oepnv marine fixme
    TILEID=71400001
    COUNTRY_ABBR="CAN"
    SPLITTER_MAXNODES=1200000
    ;;
usa*)
    MAPS="basemap" # oepnv wanderwege bicycling marine fixme
    COUNTRY_ABBR="USA"
    case "$COUNTRY" in
	usa-northeast)
	    TILEID=71500001
	    ;;
	usa-west)
	    TILEID=71500501
	    ;;
	usa-midwest)
	    TILEID=71501001
	    ;;
	usa-south)
	    TILEID=71501501
	    ;;
	usa-caribbean)
	    TILEID=71520001
	    ;;
    esac
    ;;
portugal)
    MAPS="basemap bicycling oepnv wanderwege" # marine
    TILEID=72500001
    COUNTRY_ABBR="PRT"
    ;;
scandinavia)
    MAPS="basemap bicycling oepnv wanderwege" # marine fixme
    TILEID=71900001
    COUNTRY_ABBR="DNS"
    ;;
spain)
    MAPS="basemap bicycling oepnv wanderwege" # marine
    TILEID=72400001
    COUNTRY_ABBR="ESP"
    ;;
canary_islands)
    MAPS="basemap bicycling oepnv wanderwege" # marine
    TILEID=72400201
    COUNTRY_ABBR="ESP"
    ;;
new_zealand)
    MAPS="basemap wanderwege" # bicycling oepnv marine
    TILEID=72600001
    COUNTRY_ABBR="NZL"
    ;;
monaco)
    MAPS="basemap" # bicycling oepnv wanderwege marine
    TILEID=72680001
    COUNTRY_ABBR="MCO"
    ;;
singapore)
    MAPS="basemap" # bicycling oepnv wanderwege marine
    TILEID=72660001
    COUNTRY_ABBR="SGP"
    ;;
*)
    echo "Country unknown!"
    exit 1
    ;;
esac

DESC="TK-${CAPCOUNTRY}-Tile"

BASE_IS_SPLITTED=NO
OSMBUGS_IS_SPLITTED=NO

for style in $MAPS ; do
    case "$style" in
	srtm)
	    SplitIntoTiles data/srtm tiles-srtm
	    ;;
	osb)
	    if [ "$OSMBUGS_IS_SPLITTED" == "NO" ] ; then
		/usr/bin/time tk-osm/scripts/update_osmbugs
		if [ $? -ne 0 ] ; then
		    echo "update_osmbugs for $COUNTRY failed!"
		else
		    SplitIntoTiles data/osmbugs tiles-osmbugs
		    OSMBUGS_IS_SPLITTED=YES
		fi
	    fi
	    ;;
	*)
	    if [ "$BASE_IS_SPLITTED" == "NO" ] ; then
		SplitIntoTiles data/osm tiles
		BASE_IS_SPLITTED=YES
	    fi
	    ;;
    esac
    echo "Building $style ..."
    rm -rf "build/$COUNTRY/$style"

    /usr/bin/time tk-osm/scripts/create_map "$style" "$COUNTRY" "$COUNTRY_ABBR"
    if [ $? -ne 0 ] ; then
	echo "create_map for $style failed!"
	RETVAL=1
	continue
    fi

    /usr/bin/time tk-osm/scripts/create_7z "$style" "$COUNTRY"
    if [ $? -ne 0 ] ; then
	echo "create_7z for $style failed!"
	RETVAL=1
	continue
    fi
done

exit $RETVAL
