#!/bin/bash

INPUTDIR=${1:-data/planet}
DATADIR=${2:-data/osm}

set -o nounset
#set -o errexit

onerror()
{
  cleanup 2
}

cleanup()
{
  rm -rf .tmp
  popd > /dev/null
  exit $1
}

trap onerror INT TERM

print_date()
{
  echo -n "Timestamp: "
  date +"%F %k:%M"
}

# check timestamp.txt content if we have a newer input file
cmp -s "${INPUTDIR}/timestamp.txt" "${DATADIR}/timestamp.txt"
if [ $? -eq 0 ] ; then
  echo "No new input file to extract from"
  exit 1
fi

INPUT=$(/bin/ls "${INPUTDIR}"/planet-*.osm.pbf | sort -r | head -1)

echo "Extract countries from $INPUT ..."

rm -rf "${DATADIR}/.tmp"
mkdir -p "${DATADIR}/.tmp" || exit 2

echo "osmium extract world"
print_date
osmium extract -c tk-osm/scripts/osmium-extract/planet.json "${INPUT}"
if [ $? -ne 0 ] ; then
  echo "Extracting from planet failed"
  cleanup 2
fi

echo "osmium extract europe 1"
print_date
osmium extract -c tk-osm/scripts/osmium-extract/europe1.json data/osm/.tmp/europe.osm.pbf
if [ $? -ne 0 ] ; then
  echo "Eextracting from europe 1 failed"
  cleanup 2
fi
echo "osmium extract europe 2"
print_date
osmium extract -c tk-osm/scripts/osmium-extract/europe2.json data/osm/.tmp/europe.osm.pbf
if [ $? -ne 0 ] ; then
  echo "Eextracting from europe 2 failed"
  cleanup 2
fi
echo "osmium extract europe 3"
print_date
osmium extract -c tk-osm/scripts/osmium-extract/europe3.json data/osm/.tmp/europe.osm.pbf
if [ $? -ne 0 ] ; then
  echo "Eextracting from europe 3 failed"
  cleanup 2
fi

echo "osmium extract USA"
print_date
osmium extract -c tk-osm/scripts/osmium-extract/usa.json data/osm/.tmp/usa.osm.pbf
if [ $? -ne 0 ] ; then
  echo "Extracting from usa failed"
  exit 2
fi

print_date

mv "${DATADIR}"/.tmp/* "${DATADIR}/"
cp -av "${INPUTDIR}/timestamp.txt" "${DATADIR}/timestamp.txt"
rmdir "${DATADIR}/.tmp"
